"""Platform inspection, Samsung Galaxy hardware detection, memory checks, and Android OS bridges."""

import logging
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, Optional, Tuple

logger = logging.getLogger("termux_diffusion.platform")

# Android Termux standard paths
TERMUX_PREFIX = os.environ.get("PREFIX", "/data/data/com.termux/files/usr")
TERMUX_HOME = os.environ.get("HOME", "/data/data/com.termux/files/home")


def is_android_termux() -> bool:
    """Check whether the current runtime environment is native Android Termux."""
    if os.environ.get("TERMUX_VERSION") or os.environ.get("TERMUX_APP_PID"):
        return True
    if os.path.exists("/data/data/com.termux"):
        return True
    if os.path.exists(f"{TERMUX_PREFIX}/bin/pkg"):
        return True
    return False


def is_arm64() -> bool:
    """Check whether the host CPU architecture is 64-bit ARM (aarch64 / arm64)."""
    machine = platform.machine().lower()
    return machine in ("aarch64", "arm64", "armv8l", "armv8b")


def get_default_cache_dir() -> Path:
    """Return default cache directory for models and downloaded assets."""
    custom_cache = os.environ.get("TERMUX_DIFFUSION_CACHE")
    if custom_cache:
        path = Path(os.path.expanduser(custom_cache)).resolve()
    else:
        path = Path(os.path.expanduser("~/.cache/termux-diffusion")).resolve()
    path.mkdir(parents=True, exist_ok=True)
    return path


def get_galaxy_gallery_dir() -> Path:
    """Resolve and ensure the Samsung Galaxy / Android media pictures directory."""
    # Preferred: ~/storage/pictures/TermuxDiffusion
    user_pictures = Path(os.path.expanduser("~/storage/pictures/TermuxDiffusion"))
    if user_pictures.parent.exists():
        user_pictures.mkdir(parents=True, exist_ok=True)
        return user_pictures

    # Secondary: /storage/emulated/0/Pictures/TermuxDiffusion
    sdcard_pictures = Path("/storage/emulated/0/Pictures/TermuxDiffusion")
    try:
        sdcard_pictures.mkdir(parents=True, exist_ok=True)
        return sdcard_pictures
    except (PermissionError, OSError):
        pass

    # Fallback to local workspace output directory
    fallback = get_default_cache_dir() / "outputs"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback


def export_to_android_gallery(source_image_path: Path, destination_name: Optional[str] = None) -> Path:
    """Copy rendered image to Samsung Gallery directory and broadcast media scanner intent.
    
    This ensures that images generated by termux-diffusion appear immediately in
    the Samsung Gallery app without requiring a reboot.
    """
    source_image_path = Path(source_image_path).resolve()
    if not source_image_path.exists():
        raise FileNotFoundError(f"Source image does not exist: {source_image_path}")

    dest_dir = get_galaxy_gallery_dir()
    if destination_name is None:
        destination_name = source_image_path.name

    dest_path = dest_dir / destination_name
    shutil.copy2(source_image_path, dest_path)
    logger.info("Exported AI image to Samsung Gallery path: %s", dest_path)

    # Broadcast media scanner intent if on Android
    _trigger_media_scanner(dest_path)
    return dest_path


def _trigger_media_scanner(image_path: Path) -> None:
    """Broadcast android.intent.action.MEDIA_SCANNER_SCAN_FILE so Galaxy Gallery indexes the file."""
    if not is_android_termux():
        return

    am_binary = shutil.which("am") or shutil.which("termux-am")
    if not am_binary:
        return

    file_uri = f"file://{image_path.resolve()}"
    try:
        subprocess.run(
            [am_binary, "broadcast", "-a", "android.intent.action.MEDIA_SCANNER_SCAN_FILE", "-d", file_uri],
            capture_output=True,
            timeout=3.0,
            check=False
        )
    except Exception as exc:
        logger.debug("Media scanner broadcast note: %s", exc)


def get_optimal_thread_count() -> int:
    """Calculate the optimal number of inference threads for Galaxy Exynos / Snapdragon CPUs.
    
    In big.LITTLE architectures (e.g. 4 Performance + 4 Efficiency cores), running on all 8
    cores causes severe thermal throttling and cache thrashing. Using the performance cluster
    count (typically 4 threads) yields faster inference and lower heat.
    """
    total_cores = os.cpu_count() or 4
    if total_cores >= 8:
        return 4
    elif total_cores >= 6:
        return 4
    elif total_cores >= 4:
        return 4
    return max(1, total_cores)


def get_memory_info() -> Dict[str, int]:
    """Inspect /proc/meminfo to retrieve RAM and Samsung RAM Plus (zRAM swap) metrics in MB."""
    metrics = {
        "mem_total_mb": 0,
        "mem_available_mb": 0,
        "swap_total_mb": 0,
        "swap_free_mb": 0,
        "effective_total_mb": 0,
        "effective_available_mb": 0,
    }
    
    if not os.path.exists("/proc/meminfo"):
        # Fallback for mock/test environments
        metrics["mem_total_mb"] = 6144
        metrics["mem_available_mb"] = 3072
        metrics["swap_total_mb"] = 4096
        metrics["swap_free_mb"] = 4096
        metrics["effective_total_mb"] = 10240
        metrics["effective_available_mb"] = 7168
        return metrics

    try:
        with open("/proc/meminfo", "r", encoding="utf-8") as f:
            for line in f:
                parts = line.split(":")
                if len(parts) == 2:
                    key = parts[0].strip()
                    val_str = parts[1].strip().split()[0]
                    if val_str.isdigit():
                        val_kb = int(val_str)
                        val_mb = val_kb // 1024
                        if key == "MemTotal":
                            metrics["mem_total_mb"] = val_mb
                        elif key == "MemAvailable":
                            metrics["mem_available_mb"] = val_mb
                        elif key == "SwapTotal":
                            metrics["swap_total_mb"] = val_mb
                        elif key == "SwapFree":
                            metrics["swap_free_mb"] = val_mb
    except Exception as e:
        logger.debug("Failed reading /proc/meminfo: %s", e)

    metrics["effective_total_mb"] = metrics["mem_total_mb"] + metrics["swap_total_mb"]
    metrics["effective_available_mb"] = metrics["mem_available_mb"] + metrics["swap_free_mb"]
    return metrics


def check_memory_safety(required_mb: int = 1500) -> Tuple[bool, str]:
    """Verify if available memory is sufficient for model loading without triggering Android LMK."""
    mem = get_memory_info()
    avail = mem["effective_available_mb"]
    if avail < required_mb:
        return False, (
            f"Available memory ({avail} MB) is below the recommended threshold ({required_mb} MB). "
            f"Please enable Samsung RAM Plus (Settings -> Battery and device care -> Memory -> RAM Plus) "
            f"or close background apps to avoid Low Memory Killer (LMK) termination."
        )
    return True, f"Memory check passed: {avail} MB available (RAM + zRAM)."


class TermuxWakeLock:
    """Context manager to hold Android CPU WakeLock during long-running AI inference."""
    
    def __init__(self, enabled: bool = True):
        self.enabled = enabled
        self._acquired = False

    def __enter__(self):
        if not self.enabled or not is_android_termux():
            return self

        wake_lock_bin = shutil.which("termux-wake-lock")
        if wake_lock_bin:
            try:
                subprocess.run([wake_lock_bin], capture_output=True, timeout=2.0, check=False)
                self._acquired = True
                logger.debug("Acquired Termux CPU WakeLock.")
            except Exception as e:
                logger.debug("Failed acquiring WakeLock: %s", e)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self._acquired:
            wake_unlock_bin = shutil.which("termux-wake-unlock")
            if wake_unlock_bin:
                try:
                    subprocess.run([wake_unlock_bin], capture_output=True, timeout=2.0, check=False)
                    logger.debug("Released Termux CPU WakeLock.")
                except Exception as e:
                    logger.debug("Failed releasing WakeLock: %s", e)
            self._acquired = False
